---
- name: Checkout influxdb library src
  git:
    repo: "https://github.com/offa/influxdb-cxx"
    dest: "/usr/local/src/influxdb-cxx"
    update: yes
  tags: git
  become: yes

- name: Ensure influxdb build directory exists
  file:
    state: directory
    path: "/usr/local/src/influxdb-cxx/build"
  become: yes

- name: symlink make to gmake so the Ansible module works
  file:
    state: link
    src: /usr/bin/make
    dest: /usr/bin/gmake
  become: yes

- name: Make Install influxdb
  make:
    chdir: /usr/local/src/influxdb-cxx/build
    target: install
    params:
      INFLUXCXX_TESTING:BOOL: "OFF"
  become: yes
