---
- name: Pilzpush 
  hosts: all
  gather_facts: yes
  pre_tasks:
    - include_tasks: ../tasks/pi.yml
      tags: pre_tasks
  roles:
    - role: ../roles/pilzpush-ansible-influxdb
      tags:
        - database 
    - role: ../roles/pilzpush-ansible-grafana
      tags:
        - blick
    - role: ../roles/pilzpush-ansible-collector
      tags:
        - col

